### ISSUE TITLE
그룹 생성 및 가입 선택 페이지 구현: 스프링 시작 Step1

### ISSUE THREAD

**Issue by yeeuniii** [Buddies2024/spring#130]
## 작업 요약
그룹 생성 및 가입 선택 페이지 구현

### 작업 세부 사항
- [x] 배경 구현
- [x] 그룹 가입 / 생성 버튼 구현
- [x] 스텝 넘어갈때마다 채워지는거 구현
- [x] 다음 스텝으로 넘어가는거 구현

### 스크린샷
<img width="394" alt="Screenshot 2024-10-01 at 4 04 35 PM" src="https://github.com/user-attachments/assets/bccd0603-d5a9-48a5-ad3d-0eccc7129d94">

**Comment by yeeuniii** [comment]
이슈 잘못 연결함 🥺
- [feat: 그룹 생성 및 가입 선택 버튼 및 텍스트 구현](https://github.com/Buddies2024/spring/commit/c0dc3a06f87f53fcd78f897add20e625b3222cb8) c0dc3a0
- [feat: 버튼 클릭시 질문텍스트 추가 및 색 바꾸기](https://github.com/Buddies2024/spring/commit/3313e3069768121f71141ced938446c0b902e91e) 3313e30

**Comment by yeeuniii** [comment]
https://github.com/user-attachments/assets/a9b21759-d277-496a-a5bd-bc4ad92e46d3

시작 화면에서 버튼을을 클릭하면 텍스트가 살짝 올라가는 이슈가 있는데 와 이럴까요...? 🥺 @redparkchu

**Comment by yeeuniii** [comment]
<img width="250" alt="Screenshot 2024-10-11 at 12 44 04 AM" src="https://github.com/user-attachments/assets/930ccda5-dbef-40b6-96db-e42ca7874845">
<img width="250" alt="Screenshot 2024-10-11 at 12 44 09 AM" src="https://github.com/user-attachments/assets/b0168dce-8f4d-4f78-ba75-fda880c8bbc4">
<img width="250" alt="Screenshot 2024-10-11 at 12 44 14 AM" src="https://github.com/user-attachments/assets/86e1236b-0cdf-4a97-ab9e-419b6e085172">

- 위 문제 제외하고는 페이지 구현 완료되었습니다!

**Comment by redparkchu** [comment]
@yeeuniii 
그룹 가입/생성 페이지의 기본틀을 만들어 봤어요.

`step-content` 내부에 각 스텝의 UI가 들어갈거에요.

UI 그리는 방법은 step 별 js 를 분리하고
분리한 js 내부에 해당 스텝의 html 코드를 가지는 상수값으로 `STEP1_HTML` 을 줄거에요.
해당 html 코드를 이용해 `drawStep1` 메소드가 화면을 그려주고 `drawStep1` 메소드 내부에서 `initStep1` 메소드를 호출해
새로 그려준 화면에 이벤트를 넣어줄거에요.

**Comment by redparkchu** [comment]
흐름 관련된 코드는 `group-common.js` 에서 진행될 예정이며 
아직 구현중이라 추후 구현이 끝나고 추가로 코멘트 달아서 사용방법 알려드릴게요! 😄

**Comment by redparkchu** [comment]
우선 https://github.com/Buddies2024/spring/issues/130#issuecomment-2408583379 해당 코멘트를 기준으로 다른 스텝들 코드도 바꿔주세요!

**Comment by redparkchu** [comment]
@yeeuniii @jisunggi 
https://github.com/Buddies2024/spring/issues/130#issuecomment-2408583379 요 코멘트에서
step-content -> note-body 로 수정되었습니다..!

**Comment by redparkchu** [comment]
구조가 계속 변경될거 같은데.. 죄송합니다 ㅠㅠ 시간이 너무 부족하네용..
내일 아침에 흐름 관련 마무리 짓고 커밋할게요.
죄송합니다 😭

**Comment by yeeuniii** [comment]
그럼 우리 못해뇨???? 하지미요????

2024년 10월 12일 (토) 오후 11:48, 박주한 ***@***.***>님이 작성:

**Comment by yeeuniii** [comment]
그럼 저희 오늘 새벽 작업 못하나용??

**Comment by yeeuniii** [comment]
<img width="1277" alt="Screenshot 2024-10-13 at 12 30 09 AM" src="https://github.com/user-attachments/assets/6033cba0-3fed-4e8d-be25-fdfa283e6813">
`content` css의 heignt이 커서 전체 페이지에 스크롤이 생기는 이슈가 있네요. 높이를 좀 줄이는 거 어떨까요?

**Comment by redparkchu** [comment]
@yeeuniii 
제 크롬에선 스크롤이 안생겨서 문제가 없는줄 알았는데 그냥 안생기는 거였네요..
예은님이 `content` 의 height 을 몇정도로 해야 스크롤이 발생하지 않는지 알려주시면 반영할게요 :)

**Comment by redparkchu** [comment]
@yeeuniii @jisunggi 
스텝별 흐름 관련 기능 구현이 완료되었어요.
`nextStep` 메소드를 통해 다음 스텝으로 이동하고
`prevStep` 메소드를 통해 이전 스텝으로 이동합니다.
각 스텝을 그려주는 코드는 `group-common.js` 파일에 있는 `steps` 에 넣어주시면 됩니다!
```
const steps = {
    1: drawStep1,
    2: drawStep2,
    3: drawStep3,
    4: drawStep4,
    5: drawStep5
}
```
`group-step1.js` 파일을 참고하여 구현해주세요~ 😄

**Comment by redparkchu** [comment]
테스트를 위해서 크롬의 관리자 도구에서 console 탭으로 이동한 후
`nextStep` , `prevStep` 메소드를 호출해주시면 됩니다.

**Comment by redparkchu** [comment]
추가로 그룹 생성/가입 API 관련하여 어떻게 요청하면 될까요?

**Comment by redparkchu** [comment]
@yeeuniii @jisunggi 
찐으로 스텝별 흐름 관련 기능 구현이 완료되었어요.
`nextStep` 메소드를 통해 다음 스텝으로 이동하고
`prevStep` 메소드를 통해 이전 스텝으로 이동합니다.
각 스텝을 그려주는 코드는 `group-common.js` 파일에 있는 `steps` 에 넣어주시면 됩니다!
각 스텝별 확인 버튼에 대한 이벤트 처리는 `group-common.js` 파일에 있는 `steps` 에 넣어주시면 됩니다!
스텝2 처럼 분기가 나뉘는 경우 `steps[2].draw = draw 메소드` 처럼 상황에 따라 바꿔주신후 `nextStep` 메소드를 호출하시면 됩니다.
```
const steps = {
    1: {
            "draw": drawStep1,
            "confirm": confirmStep1
    },
    2: {
            "draw": drawStep2,
            "confirm": confirmStep2
    },
    3: {
            "draw": drawStep3,
            "confirm": confirmStep3
    },
    4: {
            "draw": drawStep4,
            "confirm": confirmStep4
    },
    5: {
            "draw": drawStep5,
            "confirm": confirmStep5
    }
}
```

스텝별 데이터 저장은 아래와 같이 `group-common.js` 파일에 있는 `groupData` 가 담당하고 있습니다.
```
const groupData = {
    "groupId": "",
    "groupName": "",
    "profileLocation": "",
    "nickname": ""
}
```
### step2
`groupId` 는 그룹 가입시에만 데이터가 저장될 예정입니다.
`groupName` 은 그룹 생성시 데이터가 저장될 예정입니다.
따라서 그룹 가입과 생성을 구분짓는건 `groupId` 의 유무라고 생각해주시면 될것 같습니다.

### step3
`profileLocation` 은 캐릭터를 선택하면 데이터가 저장될 예정입니다.

### step4
`nickname` 은 본인의 닉네임을 입력하면 데이터가 저장될 예정입니다.

### step5
`groupData` 를 바탕으로 API 요청을 할 예정입니다.

---

`group-step1.js` 파일을 참고하여 구현해주세요~ 😄
