### ISSUE TITLE
개인 캐릭터 선택 페이지 구현: 스프링 시작 Step3

### ISSUE THREAD

**Issue by yeeuniii** [Buddies2024/spring#132]
## 작업 요약
개인 캐릭터 선택 페이지 구현

### 작업 세부 사항
- [x] 캐릭터 배치
- [x] 클릭 시 노란 원
- [x] 프로필 이미지 선택 조회 API 통해서 회색 캐릭터 배치
- [x] 프로필 선택 후 확인 클릭 시 저장

### 스크린샷
<img width="305" alt="Screenshot 2024-10-01 at 4 08 25 PM" src="https://github.com/user-attachments/assets/23a25416-234e-4b71-b250-5e3260f6017a">

**Comment by yeeuniii** [comment]
@redparkchu 캐릭터 클릭시 노란색 원 밖에 뜨게하는거 우케하나용 ㅠㅠ?

**Comment by redparkchu** [comment]
@yeeuniii 
잘 👍
