### ISSUE TITLE
에러 모달 창 구현

### ISSUE THREAD

**Issue by jisunggi** [Buddies2024/spring#161]
## 작업 요약
에러 모달 창 구현

### 작업 세부 사항
- [ ] 에러 모달
- [ ] html

### 스크린샷
<img width="305" alt="스크린샷 2024-10-06 오전 3 14 51" src="https://github.com/user-attachments/assets/06b7ea43-c6d3-488b-9d82-e610afed0267">

**Comment by yeeuniii** [comment]
#176 이슈에서 작업 완료. 재사용할 예정
