### ISSUE TITLE
일기 조회 인가

### ISSUE THREAD

**Issue by jisunggi** [Buddies2024/spring#254]
## 작업 요약
일기 조회 인가 구현

### 작업 세부 사항
- [x] 일기 조회 인가를 위한 장치 추가
  - 사용자 테이블에 `last_viewable_diary_date` 컬럼 추가
- [x] 일기 조회 인터셉터 구현
- [x] url 연결
  - /group/{groupId}/diary/{diaryId}
- [x] 테스트 작성

**Comment by yeeuniii** [comment]
> 🤔 일기 조회 인가를 어떻게 할 것인가?

가장 간단하게는
1. 내 순서일때는 다 볼 수 있음
2. 내 순서가 아니라면, 
내가 마지막으로 작성한 일기까지 볼 수 있는 것.

다만 `일기 건너뛰기` 기능때문에 위 규칙이 무너질 수 있음.

따라서 새로운 장치를 추가해야할 것 같은데, 
1. 일기 인덱스 추가하기
2. 사용자한테 조회 가능한 마지막 일기 날짜 추가하기 
➡️ 채택!! `last_viewable_diary_order `
